default['workstation']['aws_s3_bucket'] = 'bucket'
default['workstation']['aws_access_key_id'] = 'id'
default['workstation']['aws_secret_access_key'] = 'secret'
default['workstation']['user'] = 'user'
default['workstation']['password'] = 'password'
